api:
  username: USERNAME
  password: PASSWORD
  forceConnect: true
bot:
  level-guard:
    enabled: false
    warning-limit: 3
    allow-guests: true
    min-level: 0
    max-level: 9001
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/amq_contest_bot
    username: amq_contest_bot
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
